### ISSUE TITLE
unexpected EOF while parsing

### ISSUE THREAD

**Issue by ghost** [DDDASHXD/zoombrute#1]
Input a proxy, press enter for none.
eg: 1.1.1.1:1111

Traceback (most recent call last):
  File "main.py", line 17, in <module>
    PROXY = input()
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing

**Comment by die-dimitry** [comment]
getting same error. Admin plz revert back

**Comment by johnmalib** [comment]
Unexpected [EOF](http://net-informations.com/python/err/eof.htm)( End Of File ) while parsing is a syntax error which means the end of source code is reached even before all the blocks of code are completed. This happens in a number of situations in Python, such as:

- Missing or unmatched parentheses.
- Forget to enclose code inside a special statement.
- Unfinished try statement.

To solve this error, first check to make sure that every if statement, for loop, while loop, try statement and function contains code. Second, check to make sure you close all the parenthesis in your code. Moreover, you can avoid this problem by keeping code neat and readable, making it easier to find and fix the problem whenever the error does occur.
